# Tensor 계산을 GPU로

In [2]:
x = torch.rand(3,3)
y = torch.rand(3,3)

In [3]:
if torch.cuda.is_available() :
    x = x.cuda()
    y = y.cuda()
    sum = x+y

# Variable

### Autograd : automatic differentiation
* Autograd를 사용하면 backprop를 위한 미분 값을 자동으로 계산해줍니다.
* 자동 계산을 위해서 사용하는 변수는 torch.autogard에 있는 Variable

### autograd.Variable
* data, grad, grad_fn 3가지로 구성
> * data : Tensor 형태의 데이터가 담김
> * grad : Data가 거쳐온 layer에 대한 미분값이 축적됨
> * grad_fn : 미분 값을 계산한 함수에 대한 정보(어떤 연산에 대한 back)

In [54]:
import torch
from torch.autograd import Variable

In [55]:
x = torch.ones(3)
x = Variable(x, requires_grad = True)

In [44]:
print(x.data)
print(x.grad)
print(x.grad_fn)

tensor([1., 1., 1.])
None
None


In [56]:
y = (x**2)
z = y*3

In [57]:
# z = 3*x^2. z를 x에 대해서 미분 -> 2*3*x -> 6
# out = z.sum()
# out.backward()
grad = torch.Tensor([0.1, 1, 10])
z.backward(grad)

In [58]:
print(x.data)
print(x.grad)
print(x.grad_fn)

tensor([1., 1., 1.])
tensor([ 0.6000,  6.0000, 60.0000])
None


In [49]:
print(z.data)
print(z.grad)
print(z.grad_fn)

tensor([3., 3., 3.])
None


In [50]:
print(y.data)
print(y.grad)
print(y.grad_fn)

tensor([1., 1., 1.])
None
